
// LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_PROCESSING = 'LOGIN_PROCESSING'
export const LOGIN_FAILED = 'LOGIN_FAILED'

// USER MANAGEMENT
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_PROCESSING = 'ADD_USER_PROCESSING'
export const ADD_USER_FAILED = 'ADD_USER_FAILED'

export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS'
export const GET_ALL_USER_PROCESSING = 'GET_ALL_USER_PROCESSING'

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_PROCESSING = 'UPDATE_USER_PROCESSING'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

// FORGOT PASSWORD
export const EMAIL_SENDING_SUCCESS = 'EMAIL_SENDING_SUCCESS'
export const EMAIL_SENDING_PROCESSING = 'EMAIL_SENDING_PROCESSING'
export const EMAIL_SENDING_FAILED = 'EMAIL_SENDING_FAILED'

// LAYOUTS MANAGEMENT
export const ADD_LAYOUT_SUCCESS = 'ADD_LAYOUT_SUCCESS'
export const ADD_LAYOUT_PROCESSING = 'ADD_LAYOUT_PROCESSING'
export const ADD_LAYOUT_FAILED = 'ADD_LAYOUT_FAILED'

export const GET_ALL_LAYOUTS_SUCCESS = 'GET_ALL_LAYOUTS_SUCCESS'

export const UPDATE_LAYOUT_SUCCESS = 'UPDATE_LAYOUT_SUCCESS'
export const UPDATE_LAYOUT_PROCESSING = 'UPDATE_LAYOUT_PROCESSING'
export const UPDATE_LAYOUT_FAILED = 'UPDATE_LAYOUT_FAILED'

// PAGES MANAGEMENT
export const ADD_PAGES_SUCCESS = 'ADD_PAGES_SUCCESS'
export const ADD_PAGES_PROCESSING = 'ADD_PAGES_PROCESSING'
export const ADD_PAGES_FAILED = 'ADD_PAGES_FAILED'

export const GET_ALL_PAGES_SUCCESS = 'GET_ALL_PAGES_SUCCESS'

export const UPDATE_PAGE_SUCCESS = 'UPDATE_PAGE_SUCCESS'
export const UPDATE_PAGE_PROCESSING = 'UPDATE_PAGE_PROCESSING'
export const UPDATE_PAGE_FAILED = 'UPDATE_PAGE_FAILED'


// BLOGS MANAGEMENT
export const ADD_BLOGS_SUCCESS = 'ADD_BLOGS_SUCCESS'
export const ADD_BLOGS_PROCESSING = 'ADD_BLOGS_PROCESSING'
export const ADD_BLOGS_FAILED = 'ADD_BLOGS_FAILED'

export const GET_ALL_BLOGS_SUCCESS = 'GET_ALL_BLOGS_SUCCESS'

export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS'
export const UPDATE_BLOG_PROCESSING = 'UPDATE_BLOG_PROCESSING'
export const UPDATE_BLOG_FAILED = 'UPDATE_BLOG_FAILED'


// TAGS MANAGEMENT
export const ADD_TAGS_SUCCESS = 'ADD_TAGS_SUCCESS'
export const ADD_TAGS_PROCESSING = 'ADD_TAGS_PROCESSING'
export const ADD_TAGS_FAILED = 'ADD_TAGS_FAILED'

export const GET_ALL_TAGS_SUCCESS = 'GET_ALL_TAGS_SUCCESS'

export const UPDATE_TAG_SUCCESS = 'UPDATE_TAG_SUCCESS'
export const UPDATE_TAG_PROCESSING = 'UPDATE_TAG_PROCESSING'
export const UPDATE_TAG_FAILED = 'UPDATE_TAG_FAILED'

// TEMPLATES MANAGEMENT
export const ADD_TEMPLATES_SUCCESS = 'ADD_TEMPLATES_SUCCESS'
export const ADD_TEMPLATES_PROCESSING = 'ADD_TEMPLATES_PROCESSING'
export const ADD_TEMPLATES_FAILED = 'ADD_TEMPLATES_FAILED'

export const GET_ALL_TEMPLATES_SUCCESS = 'GET_ALL_TEMPLATES_SUCCESS'

export const UPDATE_TEMPLATE_SUCCESS = 'UPDATE_TEMPLATE_SUCCESS'
export const UPDATE_TEMPLATE_PROCESSING = 'UPDATE_TEMPLATE_PROCESSING'
export const UPDATE_TEMPLATE_FAILED = 'UPDATE_TEMPLATE_FAILED'
